<a href="https://colab.research.google.com/github/martinondiwa/Numpy/blob/main/Lists.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [33]:
import numpy as np

In [34]:
print(np.__version__)

2.0.2


In [35]:
#creating a list of numbers
my_list = [1,2,3,4]

In [36]:
print(my_list)


[1, 2, 3, 4]


In [37]:
#multiplying my list by 2 (this is a normal python array)
my_list = my_list * 2
print(my_list)

[1, 2, 3, 4, 1, 2, 3, 4]


In [38]:
#Creating a numpy array
array = np.array([1, 2, 3, 4])
print(array)

[1 2 3 4]


In [39]:
#Checking the type of array
#nd means number of dimensions
print(type(array))
array = array * 2
print(array)

<class 'numpy.ndarray'>
[2 4 6 8]


In [40]:
from pathlib import PureWindowsPath
# zero dimensional array
array = np.array('A')
print(array.ndim)

0


In [41]:
#multidimensional array
array = np.array([[1, 2, 3], [4, 5, 6]])
print(array)
print(array.ndim)



[[1 2 3]
 [4 5 6]]
2


In [42]:
#when you arrange them downwards they form like a 2D matrix
#to achieve 2d array close the matrix within another matrix and add another list
array = np.array([['k', 'g', 'f', 'h'],
                  ['a', 'b', 'c', 'd'],
                  ['g', 'g', 'f', 'r']])
print(array.ndim)


2


In [43]:
#3D array


In [44]:
#when you arrange them downwards they form like a 2D matrix
#pay attention to the number of brackets
array = np.array([[[1, 2, 3, 4]],
                  [['a', 'b', 'c', 'd']],
                  [['g', 'g', 'f', 'r']]])

print(array.ndim)
print (array.shape)


3
(3, 1, 4)


In [45]:
#when you arrange them downwards they form like a 2D matrix
#pay attention to the number of brackets
array = np.array([[[1, 2, 3, 4], ],
                  [['a', 'b', 'c', 'd']],
                  [['g', 'g', 'f', 'r']]])

print(array.ndim)
print (array.shape)


3
(3, 1, 4)


In [46]:
#when you arrange them downwards they form like a 2D matrix
#pay attention to the number of brackets
array = np.array([[[1, 2, 3, 4], [1, 2, 3, 4]],
                  [['a', 'b', 'c', 'd'], ['s', 'e', 't,', 'z']],
                  [['g', 'g', 'f', 'r'], ['t', 'f', 'g', 'p']]])

print(array.ndim)
print (array.shape)

# to get elements in our array we shall use their indices eaxample
#getting the first element
print(array[0][0][0])  #this is called chain indexing

#Their is also multidimensional indexing
print(array[0, 0, 0])
print(array[1, 0, 2])
print(array[1, 1, 1])

#Using string concatination to print 3 letter word from the multidimensional array
word = array[1, 0, 1] + array[0, 0, 1] + array[0, 0, 3]
print(word)


3
(3, 2, 4)
1
1
c
e
b24
