<a href="https://colab.research.google.com/github/martinondiwa/Numpy/blob/main/Scalar_arithmatic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Scalar arithmatic operations
#Scaler is arithmatic functions that means a single value

In [1]:
import numpy as np

In [7]:
#we need an array to work with
array = np.array([1,2,3])

#adding value to each element of the array
print(array + 1)

#subtracting value from each element of the array
print(array - 1)

#multiplication
print(array * 3)

#division
print(array / 2)

#raising each element to the power of 5
print(array ** 5)

#
print(array//3)

[2 3 4]
[0 1 2]
[3 6 9]
[0.5 1.  1.5]
[  1  32 243]
[0 0 1]
