<a href="https://colab.research.google.com/github/martinondiwa/Numpy/blob/main/Sclicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#column selection
array = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [13, 14, 15, 16],
                 [9, 10, 11, 12]])
#for columns you must have something on first value ':'
print(array[:, 0])
print(array[:, 0:3]) #prints first 3 columns
print(array[:, 0:3:2]) #prints first 3 columns with a step of 2
print(array[:, -1]) #prints last column
print(array[:, :: 2]) #prints every second column

#printing a row and a column
print(array[0:2, 0:2]) #gives the first two columns of the first two rows
#print(array[0, 0:3])
print(array[2:, 0:2])
#last two rows last two columns
print(array[2:, 2:])

[ 1  5 13  9]
[[ 1  2  3]
 [ 5  6  7]
 [13 14 15]
 [ 9 10 11]]
[[ 1  3]
 [ 5  7]
 [13 15]
 [ 9 11]]
[ 4  8 16 12]
[[ 1  3]
 [ 5  7]
 [13 15]
 [ 9 11]]
[[1 2]
 [5 6]]
[[13 14]
 [ 9 10]]
[[15 16]
 [11 12]]


In [ ]:
#column selection
array = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [13, 14, 15, 16],
                 [9, 10, 11, 12]])
#for columns you must have something on first value ':'
print(array[:, 0])
print(array[:, 0:3]) #prints first 3 columns
print(array[:, 0:3:2]) #prints first 3 columns with a step of 2
print(array[:, -1]) #prints last column
print(array[:, :: 2]) #prints every second column

#printing a row and a column
print(array[0:2, 0:2]) #gives the first two columns of the first two rows
#print(array[0, 0:3])
print(array[2:, 0:2])
#last two rows last two columns
print(array[2:, 2:])

[ 1  5 13  9]
[[ 1  2  3]
 [ 5  6  7]
 [13 14 15]
 [ 9 10 11]]
[[ 1  3]
 [ 5  7]
 [13 15]
 [ 9 11]]
[ 4  8 16 12]
[[ 1  3]
 [ 5  7]
 [13 15]
 [ 9 11]]
[[1 2]
 [5 6]]
[[13 14]
 [ 9 10]]
[[15 16]
 [11 12]]


In [1]:
import numpy as np

In [6]:
array = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [13, 14, 15, 16],
                 [9, 10, 11, 12]])
#array[start:end:step]
print(array[0])
#selecting a range
print(array[0:3])
print(array[0:3:2])
#Negative indexing
print(array[-1])
print(array[-1:-3])
print(array[-1:-3:-1])
#printing all the rows reversed
print(array[::-1])

[1 2 3 4]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [13 14 15 16]]
[[ 1  2  3  4]
 [13 14 15 16]]
[ 9 10 11 12]
[]
[[ 9 10 11 12]
 [13 14 15 16]]
[[ 9 10 11 12]
 [13 14 15 16]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [17]:
#column selection
array = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [13, 14, 15, 16],
                 [9, 10, 11, 12]])
#for columns you must have something on first value ':'
print(array[:, 0])
print(array[:, 0:3]) #prints first 3 columns
print(array[:, 0:3:2]) #prints first 3 columns with a step of 2
print(array[:, -1]) #prints last column
print(array[:, :: 2]) #prints every second column

#printing a row and a column
print(array[0:2, 0:2]) #gives the first two columns of the first two rows
#print(array[0, 0:3])
print(array[2:, 0:2])
#last two rows last two columns
print(array[2:, 2:])

[ 1  5 13  9]
[[ 1  2  3]
 [ 5  6  7]
 [13 14 15]
 [ 9 10 11]]
[[ 1  3]
 [ 5  7]
 [13 15]
 [ 9 11]]
[ 4  8 16 12]
[[ 1  3]
 [ 5  7]
 [13 15]
 [ 9 11]]
[[1 2]
 [5 6]]
[[13 14]
 [ 9 10]]
[[15 16]
 [11 12]]
