<a href="https://colab.research.google.com/github/martinondiwa/Numpy/blob/main/Sclicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [6]:
array = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [13, 14, 15, 16],
                 [9, 10, 11, 12]])
#array[start:end:step]
print(array[0])
#selecting a range
print(array[0:3])
print(array[0:3:2])
#Negative indexing
print(array[-1])
print(array[-1:-3])
print(array[-1:-3:-1])
#printing all the rows reversed
print(array[::-1])

[1 2 3 4]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [13 14 15 16]]
[[ 1  2  3  4]
 [13 14 15 16]]
[ 9 10 11 12]
[]
[[ 9 10 11 12]
 [13 14 15 16]]
[[ 9 10 11 12]
 [13 14 15 16]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [7]:
#column selection
array = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [13, 14, 15, 16],
                 [9, 10, 11, 12]])
