<a href="https://colab.research.google.com/github/martinondiwa/Numpy/blob/main/Vectorized_math_funcs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Element- Wise arithmatic
#we can apply operation beween two single elements within two arrays with element wise arithmatic

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

#adding individual elements in the array

print(array1 +array2)

[5 7 9]


In [3]:
import numpy as np

In [ ]:
# vectorized math funcs


In [ ]:
array = np.array([1, 2, 3])

#getting the squaroot of the elements
print(np.sqrt(array))

#getting the exponential of the elements
print(np.exp(array))

[1.         1.41421356 1.73205081]
[ 2.71828183  7.3890561  20.08553692]


In [ ]:
array = np.array([2.34, 1.45, 7.7])

#rounding off
print(np.round(array))

[2. 1. 8.]


In [ ]:
# ceiling (rounding up)

array = np.array([3.4, 2.1, 7.7])

print(np.ceil(array))

[4. 3. 8.]


In [ ]:
#printing pi
print(np.pi)

3.141592653589793


**Exercise with vectorized math functions**

In [ ]:
#given the radius of circles as an array get the areas of the circle
radii = np.array([1, 2, 3])

print (np.pi * radii**2)

[ 3.14159265 12.56637061 28.27433388]


In [ ]:
# Element- Wise arithmatic
#we can apply operation beween two single elements within two arrays with element wise arithmatic

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

#adding individual elements in the array

print(array1 +array2)
print(array1 - array2)
print(array1 * array2)
print(array1 / array2)
print(array1**array2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


 Using comparison operators, we can create boolean arrays,
filter data, and use elementwise comparisons. For this demonstration, we'll create an array of scores like test scores. Scores equals np. Call the array function. Then we'll pass in a list of scores. So these will be test scores. One student got a 91. Another got a 55. One student got a 100. Another got a 73. One student got an 82. and another got 64. Using comparison operators, let's see if any students got 100, a perfect score. What we're about to do will return a boolean array. Print array of scores that equal 100, a perfect score. We're seeing if any scores equal 100.

This will return a boolean array. It looks like there's one student that got a perfect score at element number three or index 2 012. Let's see which students got a passing score that's equal to or above 60. This is the greater than or equal to operator.
It looks like there's five students that passed. We have true, false, true, true, true, true. Or let's see if there's any
scores that are less than 60. Did any students fail? There's one. We have one true. You also could use conditional assignment. For any scores that are less than passing, less than 60, we'll assign them to be zero. So if you fail, you don't get any points, so to say. We'll take our array of scores, use the
subscript operator. Then we'll take scores less than 60. We're selecting all elements within our array where the score is less than 60. Any that are less than 60 we'll assign them to be zero and then we will print our array of scores. So now that one student would have a zero. They wouldn't get any credit if they fail. This all is a primer for filtering which is another topic
entirely but it is a good time to introduce comparison operators. All right everybody that is different forms of arithmetic in numpy. In the next topic we'll discuss broadcasting. I couldn't think of any homework for you to do. So to help engagement with this video, comment down below where is your favorite place to take a vacation and that is arithmetic using numpy.


In [ ]:
#Comparison Operators
scores = np.array([91, 55, 100, 73, 82, 64])

#Did any students get a perfect score?
print(scores == 100)
#Did any students get a passing score?
print(scores >= 60)
#Did any students get a failing score?
print(scores <= 60)

#we can also use conditional statements
#Let's assign 60 to any score below 60
#if you fail you get 0 points

print(np.where(scores < 60, 0, scores))
#or
scores[scores<60]=0
print(scores)


[False False  True False False False]
[ True False  True  True  True  True]
[False  True False False False False]
[ 91   0 100  73  82  64]
[ 91   0 100  73  82  64]


**Broadcasting**

Broadcasting allows Numpy to perform operations on arrays with different shapes by virtually expanding their dimensions.

In [ ]:
# Broadcasting allows Numpy to perform operations on arrays
# with diffent shapes by virtually expanding dimensions
# So they  match the larger array's shape

#the dimensions have the same size
#or
#one of the dimensions has a size of 1

In [ ]:
array1 = np.array([[1, 2, 3, 4, ]])
array2 = np.array([[1], [2], [3], [4]])

print(array1.shape)
print(array2.shape)

print(array1 * array2)

(1, 5)
(4, 1)
[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]]


In [ ]:
#creating a multiplication table

array1 = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])
array2 = np.array([[1], [2], [3], [4], [5], [6], [7], [8], [9], [10]])

print(array1.shape)
print(array2.shape)

#printing a multiplication table
print(array1 * array2)

(1, 10)
(10, 1)
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


**Aggregate functions**

Aggregate functions summerize data and typically return a single value

In [6]:
array = np.array([[1, 2, 3, 4, 5,],
                 [6, 7, 8, 9, 10]])

#print(np.sum(array))

# Mean/average of our array
print(np.mean(array))

#standard deviation (the measure of spread within your data)
print(np.std(array))

#variance (the variance is the square of the standard deviation)
print(np.var(array))

#printing the minimum value
print(np.min(array))

#printing the maximum value
print(np.max(array))

#getting the position of the minimum value
print(np.argmin(array))

#getting the position of the maximum value
print(np.argmax(array))

5.5
2.8722813232690143
8.25
