<a href="https://colab.research.google.com/github/martinondiwa/Numpy/blob/main/Vectorized_math_funcs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# vectorized math funcs


In [ ]:
array = np.array([1, 2, 3])

#getting the squaroot of the elements
print(np.sqrt(array))

#getting the exponential of the elements
print(np.exp(array))

[1.         1.41421356 1.73205081]
[ 2.71828183  7.3890561  20.08553692]


In [ ]:
array = np.array([2.34, 1.45, 7.7])

#rounding off
print(np.round(array))

[2. 1. 8.]


In [6]:
#rounding down
array = np.array([1.2, 3.5, 6.86])


print(np.floor(array))

[1. 3. 6.]
