In [ ]:
# Element- Wise arithmatic
#we can apply operation beween two single elements within two arrays with element wise arithmatic

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

#adding individual elements in the array

print(array1 +array2)

[5 7 9]


In [ ]:
import numpy as np

In [ ]:
# vectorized math funcs


In [ ]:
array = np.array([1, 2, 3])

#getting the squaroot of the elements
print(np.sqrt(array))

#getting the exponential of the elements
print(np.exp(array))

[1.         1.41421356 1.73205081]
[ 2.71828183  7.3890561  20.08553692]


In [ ]:
array = np.array([2.34, 1.45, 7.7])

#rounding off
print(np.round(array))

[2. 1. 8.]


In [8]:
# ceiling (rounding up)

array = np.array([3.4, 2.1, 7.7])

print(np.ceil(array))

[4. 3. 8.]


In [9]:
#printing pi
print(np.pi)

3.141592653589793


**Exercise with vectorized math functions**

In [10]:
#given the radius of circles as an array get the areas of the circle
radii = np.array([1, 2, 3])

print (np.pi * radii**2)

[ 3.14159265 12.56637061 28.27433388]


In [11]:
# Element- Wise arithmatic
#we can apply operation beween two single elements within two arrays with element wise arithmatic

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

#adding individual elements in the array

print(array1 +array2)

[5 7 9]
